frr defaults traditional
hostname l2
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.255.2/32
!
router bgp 65102
 bgp router-id 10.255.255.2
 neighbor FABRIC peer-group
 neighbor FABRIC remote-as external
 neighbor FABRIC timers 3 9
 neighbor eth1 interface peer-group FABRIC
 neighbor eth2 interface peer-group FABRIC
 !
 address-family ipv4 unicast
  maximum-paths 2
  network 10.255.255.2/32
  neighbor FABRIC route-map ALLOW-ALL in
  neighbor FABRIC route-map ALLOW-ALL out
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC route-map ALLOW-ALL in
  neighbor FABRIC route-map ALLOW-ALL out
  advertise-all-vni
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
