frr defaults traditional
hostname r4
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0.0.0.1
!
interface eth1
 ip address 10.1.34.2/30
 ip ospf area 0.0.0.1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.40.0.1/24
 ip ospf area 0.0.0.1
 ip ospf passive
!
router ospf
 ospf router-id 10.255.0.4
 log-adjacency-changes detail
!
