frr defaults traditional
hostname s2r
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 192.0.2.2/32
!
interface eth1
 ip address 100.64.21.1/30
!
interface eth2
 ip address 100.64.22.1/30
!
interface eth3
 ip address 203.0.113.1/24
!
interface eth4
 ip address 10.102.0.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface gre1
 ip address 10.99.0.2/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 192.0.2.2
 log-adjacency-changes detail
!
router bgp 65002
 bgp router-id 192.0.2.2
 neighbor 100.64.21.2 remote-as 64512
 neighbor 100.64.21.2 description ispa
 neighbor 100.64.22.2 remote-as 64513
 neighbor 100.64.22.2 description ispb
 !
 address-family ipv4 unicast
  network 203.0.113.0/24
  network 192.0.2.2/32
  neighbor 100.64.21.2 route-map ALLOW-ALL in
  neighbor 100.64.21.2 route-map ALLOW-ALL out
  neighbor 100.64.22.2 route-map ALLOW-ALL in
  neighbor 100.64.22.2 route-map ALLOW-ALL out
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
