frr defaults traditional
hostname r1
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.1/32
 ip ospf area 0.0.0.0
!
interface eth1
 ip address 10.10.0.11/24
 ip ospf area 0.0.0.0
 vrrp 10 version 3
 vrrp 10 priority 200
 vrrp 10 ip 10.10.0.1
!
interface eth2
 ip address 10.0.13.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf cost 10
!
router ospf
 ospf router-id 10.255.0.1
 log-adjacency-changes detail
!
