frr defaults traditional
hostname s1r
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 192.0.2.1/32
!
interface eth1
 ip address 100.64.11.1/30
!
interface eth2
 ip address 100.64.12.1/30
!
interface eth3
 ip address 198.51.100.1/24
!
interface eth4
 ip address 10.101.0.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface gre1
 ip address 10.99.0.1/30
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 192.0.2.1
 log-adjacency-changes detail
!
router bgp 65001
 bgp router-id 192.0.2.1
 neighbor 100.64.11.2 remote-as 64512
 neighbor 100.64.11.2 description ispa
 neighbor 100.64.12.2 remote-as 64513
 neighbor 100.64.12.2 description ispb
 !
 address-family ipv4 unicast
  network 198.51.100.0/24
  network 192.0.2.1/32
  neighbor 100.64.11.2 route-map FROM-ISPA in
  neighbor 100.64.11.2 route-map ALLOW-ALL out
  neighbor 100.64.12.2 route-map ALLOW-ALL in
  neighbor 100.64.12.2 route-map TO-ISPB out
 exit-address-family
!
route-map FROM-ISPA permit 10
 set local-preference 200
!
route-map TO-ISPB permit 10
 set as-path prepend 65001 65001 65001
!
route-map ALLOW-ALL permit 10
!
