frr defaults traditional
hostname ispb
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 100.64.255.2/32
!
interface eth1
 ip address 100.64.12.2/30
!
interface eth2
 ip address 100.64.22.2/30
!
interface eth3
 ip address 100.64.0.2/30
!
router bgp 64513
 bgp router-id 100.64.255.2
 neighbor 100.64.12.1 remote-as 65001
 neighbor 100.64.12.1 description site1
 neighbor 100.64.22.1 remote-as 65002
 neighbor 100.64.22.1 description site2
 neighbor 100.64.0.1 remote-as 64512
 neighbor 100.64.0.1 description ispa
 !
 address-family ipv4 unicast
  network 100.64.255.2/32
  neighbor 100.64.12.1 route-map ALLOW-ALL in
  neighbor 100.64.12.1 route-map ALLOW-ALL out
  neighbor 100.64.22.1 route-map ALLOW-ALL in
  neighbor 100.64.22.1 route-map ALLOW-ALL out
  neighbor 100.64.0.1 route-map ALLOW-ALL in
  neighbor 100.64.0.1 route-map ALLOW-ALL out
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
