frr defaults traditional
hostname ispa
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 100.64.255.1/32
!
interface eth1
 ip address 100.64.11.2/30
!
interface eth2
 ip address 100.64.21.2/30
!
interface eth3
 ip address 100.64.0.1/30
!
router bgp 64512
 bgp router-id 100.64.255.1
 neighbor 100.64.11.1 remote-as 65001
 neighbor 100.64.11.1 description site1
 neighbor 100.64.21.1 remote-as 65002
 neighbor 100.64.21.1 description site2
 neighbor 100.64.0.2 remote-as 64513
 neighbor 100.64.0.2 description ispb
 !
 address-family ipv4 unicast
  network 100.64.255.1/32
  neighbor 100.64.11.1 route-map ALLOW-ALL in
  neighbor 100.64.11.1 route-map ALLOW-ALL out
  neighbor 100.64.21.1 route-map ALLOW-ALL in
  neighbor 100.64.21.1 route-map ALLOW-ALL out
  neighbor 100.64.0.2 route-map ALLOW-ALL in
  neighbor 100.64.0.2 route-map ALLOW-ALL out
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
