#!/usr/bin/env python3
"""Render FRR configurations from Jinja2 templates plus per-module vars.yml.

Every router config in this repo is generated by this script. The rendered
files are committed so reviewers can read them, and so the drift checker has
a golden state to compare running configs against.
"""
import argparse
import pathlib
import sys

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
MODULES = ROOT / "modules"


def jinja_env() -> Environment:
    return Environment(
        loader=FileSystemLoader(TEMPLATES),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def render_module(module: str) -> list[pathlib.Path]:
    mdir = MODULES / module
    vars_file = mdir / "vars.yml"
    if not vars_file.exists():
        raise SystemExit(f"no vars.yml in {mdir}")
    data = yaml.safe_load(vars_file.read_text())
    env = jinja_env()
    written: list[pathlib.Path] = []
    for name, node in sorted(data["nodes"].items()):
        if node.get("role", "router") != "router":
            continue
        outdir = mdir / "configs" / name
        outdir.mkdir(parents=True, exist_ok=True)
        ctx = {"hostname": name, "node": node, "lab": data}
        for template, outname in (("frr/frr.conf.j2", "frr.conf"),
                                  ("frr/daemons.j2", "daemons")):
            text = env.get_template(template).render(**ctx)
            out = outdir / outname
            out.write_text(text, newline="\n")
            written.append(out)
    return written


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--module", help="module directory name, e.g. 01-campus-core")
    group.add_argument("--all", action="store_true", help="render every module")
    args = ap.parse_args()

    modules = ([args.module] if args.module
               else sorted(p.name for p in MODULES.iterdir()
                           if (p / "vars.yml").exists()))
    for module in modules:
        for path in render_module(module):
            print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
